### PR TITLE
Simplified setup

### PR DESCRIPTION
**Pull request by pkaul**
Moved plugin hook code for "Google PlayServices" (+Mediarouter) integration to a dedicated Cordova plugin at https://github.com/pkaul/googleplayservices-cordova-plugin. 

Integrate the new plugin by adding `cordova plugin add https://github.com/pkaul/googleplayservices-cordova-plugin.git` to the concrete Chromecast project 

This has the following advantages

- The integration code fails for some environments. Developers may then decide to not integrate this new plugin instead of having a broken built
- Clean separation of Chromecast plugin and infrastructure plugin.

### CODE REVIEW

**Comment by acidhax** [comment]
Think you could throw this into the README too?

**Comment by acidhax** [comment]
Thanks for adding it to the README! :)

**Comment by acidhax** [comment]
Any idea if this caused: https://github.com/GetVideostream/cordova-chromecast/issues/39 ?

**Comment by pkaul** [comment]
This has probably to do with the wrong oder of plugin addition. Instead of

Step 1: cordova plugin add https://github.com/GetVideostream/cordova-chromecast.git
Step 2: cordova plugin add https://github.com/pkaul/googleplayservices-cordova-plugin.git

I would try to 

Step 1: cordova plugin add https://github.com/pkaul/googleplayservices-cordova-plugin.git
Step 2: cordova plugin add https://github.com/GetVideostream/cordova-chromecast.git

**Pull request merged**
